# Generated by Django 6.0.1 on 2026-01-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="Phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
